services:
  bootnode:
    platform: linux/amd64
    image: ghcr.io/arch-network/bootnode:latest
    ports:
      - "${BOOTNODE_P2P_PORT}:${BOOTNODE_P2P_PORT}"
    environment:
      RUST_LOG: "${RUST_LOG:-info}"
      RUST_BACKTRACE: "${RUST_BACKTRACE:-1}"
      NETWORK_MODE: "${NETWORK_MODE:-localnet}"
      DATA_DIR: "/arch-data"
    volumes:
      - ./arch-data/bootnode:/arch-data
    networks:
      - arch-network

  leader:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator:latest
    ports:
      - "${LEADER_P2P_PORT}:${LEADER_P2P_PORT}"
      - "${LEADER_RPC_PORT}:${LEADER_RPC_PORT}"
    environment:
      RUST_LOG: "${RUST_LOG:-info,validator=debug}"
      RUST_BACKTRACE: "${RUST_BACKTRACE:-1}"
      NETWORK_MODE: "${NETWORK_MODE:-localnet}"
      DATA_DIR: "/arch-data"
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOT_NODE_ENDPOINT: "/dns4/bootnode/tcp/${BOOTNODE_P2P_PORT}/p2p/${BOOTNODE_PEERID}"
      LEADER_PEERID: "${LEADER_PEERID}"
      RPC_BIND_IP: "0.0.0.0"
      RPC_BIND_PORT: "${LEADER_RPC_PORT}"
      P2P_BIND_PORT: "${LEADER_P2P_PORT}"
      BITCOIN_RPC_ENDPOINT: "${BITCOIN_RPC_ENDPOINT}"
      BITCOIN_RPC_PORT: "${BITCOIN_RPC_PORT}"
      BITCOIN_RPC_USERNAME: "${BITCOIN_RPC_USERNAME}"
      BITCOIN_RPC_PASSWORD: "${BITCOIN_RPC_PASSWORD}"
      BITCOIN_RPC_WALLET: "${BITCOIN_RPC_WALLET:-devwallet}"
    volumes:
      - ./arch-data/leader:/arch-data
    depends_on:
      - bootnode
    networks:
      - arch-network

  validator-1:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator:latest
    ports:
      - "${VALIDATOR1_P2P_PORT}:${VALIDATOR1_P2P_PORT}"
      - "${VALIDATOR1_RPC_PORT}:${VALIDATOR1_RPC_PORT}"
    environment:
      RUST_LOG: "${RUST_LOG:-info,validator=debug}"
      RUST_BACKTRACE: "${RUST_BACKTRACE:-1}"
      NETWORK_MODE: "${NETWORK_MODE:-localnet}"
      DATA_DIR: "/arch-data"
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOT_NODE_ENDPOINT: "/ip4/${BOOTNODE_IP}/tcp/${BOOTNODE_P2P_PORT}/p2p/${BOOTNODE_PEERID}"
      LEADER_PEERID: "${LEADER_PEERID}"
      RPC_BIND_IP: "0.0.0.0"
      RPC_BIND_PORT: "${VALIDATOR1_RPC_PORT}"
      P2P_BIND_PORT: "${VALIDATOR1_P2P_PORT}"
      BITCOIN_RPC_ENDPOINT: "${BITCOIN_RPC_ENDPOINT}"
      BITCOIN_RPC_PORT: "${BITCOIN_RPC_PORT}"
      BITCOIN_RPC_USERNAME: "${BITCOIN_RPC_USERNAME}"
      BITCOIN_RPC_PASSWORD: "${BITCOIN_RPC_PASSWORD}"
      BITCOIN_RPC_WALLET: "${BITCOIN_RPC_WALLET:-devwallet}"
    volumes:
      - ./arch-data/validator-1:/arch-data
    depends_on:
      - bootnode
    networks:
      - arch-network

  validator-2:
    platform: linux/amd64
    image: ghcr.io/arch-network/validator:latest
    ports:
      - "${VALIDATOR2_P2P_PORT}:${VALIDATOR2_P2P_PORT}"
      - "${VALIDATOR2_RPC_PORT}:${VALIDATOR2_RPC_PORT}"
    environment:
      RUST_LOG: "${RUST_LOG:-info,validator=debug}"
      RUST_BACKTRACE: "${RUST_BACKTRACE:-1}"
      NETWORK_MODE: "${NETWORK_MODE:-localnet}"
      DATA_DIR: "/arch-data"
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOT_NODE_ENDPOINT: "/ip4/${BOOTNODE_IP}/tcp/${BOOTNODE_P2P_PORT}/p2p/${BOOTNODE_PEERID}"
      LEADER_PEERID: "${LEADER_PEERID}"
      RPC_BIND_IP: "0.0.0.0"
      RPC_BIND_PORT: "${VALIDATOR2_RPC_PORT}"
      P2P_BIND_PORT: "${VALIDATOR2_P2P_PORT}"
      BITCOIN_RPC_ENDPOINT: "${BITCOIN_RPC_ENDPOINT}"
      BITCOIN_RPC_PORT: "${BITCOIN_RPC_PORT}"
      BITCOIN_RPC_USERNAME: "${BITCOIN_RPC_USERNAME}"
      BITCOIN_RPC_PASSWORD: "${BITCOIN_RPC_PASSWORD}"
      BITCOIN_RPC_WALLET: "${BITCOIN_RPC_WALLET:-devwallet}"
    volumes:
      - ./arch-data/validator-2:/arch-data
    depends_on:
      - bootnode
    networks:
      - arch-network

networks:
  arch-network:
    ipam:
      driver: default
      config:
        - subnet: ${ARCH_NETWORK_SUBNET:-172.30.0.0/24}
          gateway: ${ARCH_NETWORK_GATEWAY:-172.30.0.1}