version: '3'
services:
  init:
    image: ${CUSTOM_VALIDATOR_IMAGE:-ghcr.io/arch-network/validator:latest}
    volumes:
      - ./arch-data:/arch_data
      - ./arch-data/bootnode:/bootnode_data
      - ./init.sh:/usr/local/bin/init.sh
    command: >
      bash -c "/usr/local/bin/init.sh"
    environment:
      - REPLICA_COUNT=2

  bootnode:
    image: ${CUSTOM_VALIDATOR_IMAGE:-ghcr.io/arch-network/bootnode:latest}
    command: /usr/local/bin/bootnode.sh
    ports:
      - "${BOOTNODE_P2P_PORT}:${BOOTNODE_P2P_PORT}"
    environment:
      RUST_LOG: "${RUST_LOG:-info}"
      RUST_BACKTRACE: "${RUST_BACKTRACE:-1}"
      BOOTNODE_P2P_PORT: "${BOOTNODE_P2P_PORT}"
      NETWORK_MODE: "${NETWORK_MODE:-localnet}"
      DATA_DIR: /arch_data
    volumes:
      - ./arch-data/bootnode:/arch_data
      - ./bootnode.sh:/usr/local/bin/bootnode.sh
    depends_on:
      - init
    networks:
      arch-network:
        ipv4_address: 172.30.0.250      

  leader:
    image: ${CUSTOM_VALIDATOR_IMAGE:-ghcr.io/arch-network/validator:latest}
    ports:
      - "${LEADER_P2P_PORT}:${LEADER_P2P_PORT}"
      - "${LEADER_RPC_PORT}:${LEADER_RPC_PORT}"
    command: /usr/local/bin/leader.sh
    environment:
      RUST_LOG: "${RUST_LOG:-info,validator=debug}"
      RUST_BACKTRACE: "${RUST_BACKTRACE:-1}"
      NETWORK_MODE: "${NETWORK_MODE:-localnet}"
      DATA_DIR: "/arch-data"
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOTNODE_P2P_PORT: "${BOOTNODE_P2P_PORT}"
      LEADER_PEERID: "${LEADER_PEERID}"
      RPC_BIND_IP: "0.0.0.0"
      RPC_BIND_PORT: "${LEADER_RPC_PORT}"
      P2P_BIND_PORT: "${LEADER_P2P_PORT}"
      BITCOIN_RPC_ENDPOINT: "bitcoin"
      BITCOIN_RPC_PORT: "${BITCOIN_RPC_PORT}"
      BITCOIN_RPC_USERNAME: "${BITCOIN_RPC_USERNAME}"
      BITCOIN_RPC_PASSWORD: "${BITCOIN_RPC_PASSWORD}"
      BITCOIN_RPC_WALLET: "${BITCOIN_RPC_WALLET:-devwallet}"
    volumes:
      - ./arch-data:/arch_data
      - ./arch-data/bootnode:/bootnode_data:ro
      - ./leader.sh:/usr/local/bin/leader.sh
    depends_on:
      - bootnode
    networks:
      - arch-network
      - internal

  validator-1:
    image: ${CUSTOM_VALIDATOR_IMAGE:-ghcr.io/arch-network/validator:latest}
    command: /usr/local/bin/validator.sh
    environment:
      VALIDATOR_NUMBER: "1"
      RUST_LOG: "${RUST_LOG:-info,validator=debug}"
      RUST_BACKTRACE: "${RUST_BACKTRACE:-1}"
      NETWORK_MODE: "${NETWORK_MODE:-localnet}"
      DATA_DIR: "/arch-data"
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOTNODE_P2P_PORT: "${BOOTNODE_P2P_PORT}"
      LEADER_PEERID: "${LEADER_PEERID}"
      RPC_BIND_IP: "0.0.0.0"
      RPC_BIND_PORT: "${VALIDATOR1_RPC_PORT}"
      P2P_BIND_PORT: "${VALIDATOR1_P2P_PORT}"
      BITCOIN_RPC_ENDPOINT: "bitcoin"
      BITCOIN_RPC_PORT: "${BITCOIN_RPC_PORT}"
      BITCOIN_RPC_USERNAME: "${BITCOIN_RPC_USERNAME}"
      BITCOIN_RPC_PASSWORD: "${BITCOIN_RPC_PASSWORD}"
      BITCOIN_RPC_WALLET: "${BITCOIN_RPC_WALLET:-devwallet}"
    volumes:
      - ./arch-data/validators:/arch_data
      - ./arch-data/bootnode:/bootnode_data:ro
      - ./validator.sh:/usr/local/bin/validator.sh
    depends_on:
      - bootnode
    ports:
      - "${VALIDATOR1_P2P_PORT}:${VALIDATOR1_P2P_PORT}"
      - "${VALIDATOR1_RPC_PORT}:${VALIDATOR1_RPC_PORT}"
    networks:
      - arch-network
      - internal

  validator-2:
    image: ${CUSTOM_VALIDATOR_IMAGE:-ghcr.io/arch-network/validator:latest}
    command: /usr/local/bin/validator.sh
    environment:
      VALIDATOR_NUMBER: "2"
      RUST_LOG: "${RUST_LOG:-info,validator=debug}"
      RUST_BACKTRACE: "${RUST_BACKTRACE:-1}"
      NETWORK_MODE: "${NETWORK_MODE:-localnet}"
      DATA_DIR: "/arch-data"
      PRIVATE_KEY_PASSWORD: "${PRIVATE_KEY_PASSWORD:-}"
      BOOTNODE_P2P_PORT: "${BOOTNODE_P2P_PORT}"
      LEADER_PEERID: "${LEADER_PEERID}"
      RPC_BIND_IP: "0.0.0.0"
      RPC_BIND_PORT: "${VALIDATOR2_RPC_PORT}"
      P2P_BIND_PORT: "${VALIDATOR2_P2P_PORT}"
      BITCOIN_RPC_ENDPOINT: "${BITCOIN_RPC_ENDPOINT}"
      BITCOIN_RPC_PORT: "${BITCOIN_RPC_PORT}"
      BITCOIN_RPC_USERNAME: "${BITCOIN_RPC_USERNAME}"
      BITCOIN_RPC_PASSWORD: "${BITCOIN_RPC_PASSWORD}"
      BITCOIN_RPC_WALLET: "${BITCOIN_RPC_WALLET:-devwallet}"
    volumes:
      - ./arch-data/validators:/arch_data
      - ./arch-data/bootnode:/bootnode_data:ro
      - ./validator.sh:/usr/local/bin/validator.sh
    depends_on:
      - bootnode
    ports:
      - "${VALIDATOR2_P2P_PORT}:${VALIDATOR2_P2P_PORT}"
      - "${VALIDATOR2_RPC_PORT}:${VALIDATOR2_RPC_PORT}"
    networks:
      - arch-network
      - internal

networks:
  arch-network:
    ipam:
      driver: default
      config:
        - subnet: ${ARCH_NETWORK_SUBNET:-172.30.0.0/24}
          gateway: ${ARCH_NETWORK_GATEWAY:-172.30.0.1}
  internal:
    external: true
    name: internal