services:
  backend:
    build: 
      context: ./src/app/backend
      args:
        DEMO_FRONTEND_PORT: ${DEMO_BACKEND_PORT}
    ports:
      - "${DEMO_BACKEND_PORT}:${DEMO_BACKEND_PORT}"
    networks:
      - arch-network

  frontend:
    build: 
      context: ./src/app/frontend
      args:
        DEMO_FRONTEND_PORT: ${DEMO_FRONTEND_PORT}
        DEMO_BACKEND_PORT: ${DEMO_BACKEND_PORT}
        INDEXER_PORT: ${INDEXER_PORT}
    ports:
      - "${DEMO_FRONTEND_PORT}:${DEMO_FRONTEND_PORT}"
    networks:
      - arch-network

networks:
  arch-network:
    external: true
    name: arch-cli_arch-network