services:
  backend:
    build: ./src/app/backend
    ports:
      - "${DEMO_BACKEND_PORT}:${DEMO_BACKEND_PORT}"
    networks:
      - arch-network

  frontend:
    build: ./src/app/frontend
    ports:
      - "${DEMO_FRONTEND_PORT}:${DEMO_FRONTEND_PORT}"
    networks:
      - arch-network

networks:
  arch-network:
    external: true
    name: arch-cli_arch-network