services:
  frontend:
    build: 
      context: ./frontend
      args:
        DEMO_FRONTEND_PORT: ${DEMO_FRONTEND_PORT}
        INDEXER_PORT: ${INDEXER_PORT}
    ports:
      - "${DEMO_FRONTEND_PORT}:${DEMO_FRONTEND_PORT}"
    networks:
      - arch-network

networks:
  arch-network:
    # external: true
    name: arch-cli_arch-network