[networks]
default = "development"

[networks.development]
type = "development"
bitcoin_rpc_endpoint = "bitcoin-node.dev.aws.archnetwork.xyz"
bitcoin_rpc_port = "18443"
bitcoin_rpc_user = "bitcoin"
bitcoin_rpc_password = "428bae8f3c94f8c39c50757fc89c39bc7e6ebc70ebf8f618"
bitcoin_rpc_wallet = "testwallet"
docker_compose_file = "./bitcoin-docker-compose.yml"
leader_rpc_endpoint = "http://host.docker.internal:9002"
services = ["local_validator"]

[networks.e2e]
type = "e2e"
bitcoin_rpc_endpoint = "localhost"
bitcoin_rpc_port = "18443"
bitcoin_rpc_user = "bitcoin"
bitcoin_rpc_password = "password"
bitcoin_rpc_wallet = "devwallet"
docker_compose_file = "./server-docker-compose.yml"
leader_rpc_endpoint = "http://localhost:9002"
services = ["bitcoin", "electrs", "btc-rpc-explorer", "local_validator"]

[networks.testnet]
type = "testnet"
bitcoin_rpc_endpoint = ""
bitcoin_rpc_port = ""
bitcoin_rpc_user = ""
bitcoin_rpc_password = ""
bitcoin_rpc_wallet = ""
leader_rpc_endpoint = "http://18.214.39.12:32323/"

[networks.mainnet]
type = "mainnet"
bitcoin_rpc_endpoint = ""
bitcoin_rpc_port = ""
bitcoin_rpc_user = ""
bitcoin_rpc_password = ""
bitcoin_rpc_wallet = ""
leader_rpc_endpoint = ""

[program]
key_path = "${CONFIG_DIR}/keys/program.json"

[electrs]
rest_api_port = "3003"
electrum_port = "60401"

[btc_rpc_explorer]
port = "3000"

[demo]
frontend_port = "5173"

[indexer]
port = "5175"

[ord]
port = "3032"

[arch]
docker_compose_file = "./arch-docker-compose.yml"
network_mode = "localnet"
rust_log = "info"
rust_backtrace = "1"
bootnode_ip = "172.30.0.10"
bootnode_p2p_port = "19001"
leader_p2p_port = "19002"
leader_rpc_port = "9002"
validator1_p2p_port = "19003"
validator1_rpc_port = "9003"
validator2_p2p_port = "19004"
validator2_rpc_port = "9004"
bitcoin_rpc_endpoint = "bitcoin"
bitcoin_rpc_wallet = "devwallet"
services = ["bootnode", "leader", "validator-1", "validator-2"]
replica_count = 2
